Cleanup
Ho1yShif/dinner pull request #11
Opened 2024-01-08 03:04 UTC by Ho1yShif

- Cleaned `meals_df` dataframe and added an explicit transpose
- Add `__str__` and `__repr__` methods to the class
- Separated functionality of google sheets authentication and JSON reading out of the `__init__` method into their own respective methods
- Corrected and added docstrings

2024-01-08 10:00 UTC, boatbomber requested changes
A few changes regarding the string representations, but the rest looks good!

2024-01-08 10:00 UTC, boatbomber commented on plan_dinners.py
> +            print(f"{day}: {meal.title()}")
String method should build a string with these- it should not take any action of its own. It should return a string, and the user decides whether to print it, store it, etc.

2024-01-08 10:00 UTC, boatbomber commented on plan_dinners.py
> +        print(self.chosen_meals)
Same critique here- it should not take action for the user.

2024-01-12 05:17 UTC, Ho1yShif commented on plan_dinners.py
> +            print(f"{day}: {meal.title()}")
Updated the method to the following:
```python
def __str__(self):
        """Return a string representation of the weekly meal plan"""

        """Schedule meals if not already scheduled"""
        if not self.meals_scheduled_flag:
            PlanDinners.schedule_meals(self)
        return '\n'.join(f"{day}: {meal.title()}" for day, meal in self.meal_schedule.items())
```

2024-01-12 05:18 UTC, Ho1yShif commented on plan_dinners.py
> +        print(self.chosen_meals)
Updated the method to the following:
```python
def __repr__(self):
        """Return a string representation of the PlanDinners object"""
        if not self.meals_scheduled_flag:
            PlanDinners.schedule_meals(self)
        return f"PlanDinners(chosen_meals={self.chosen_meals})"
```

2024-01-12 05:18 UTC, Ho1yShif commented
Fixed these issues! I'm excited to hear your thoughts :)

2024-01-12 06:18 UTC, boatbomber requested changes

2024-01-12 06:18 UTC, boatbomber commented on plan_dinners.py
> +            PlanDinners.schedule_meals(self)
This is a side effect again! It should JUST return a string that shows an empty schedule. Getting a string to log somewhere should not update my schedule or google sheet!

2024-01-14 18:26 UTC, closed without merging